name: "Test the application"
on:
  push

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: "Get the source code"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm ci
      - name: "Run tests"
        run: npm run test